### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by AlTheSlacker** [adcimon/unity-job-system-mesh-deformer#1]
This project does not have a license defined. I would like to use some of the concepts and direct copies of some of the code within for my own work, that I will make available under an MIT license on GitHub (my work is not for profit, but I like to share). Would you be OK with that or should I avoid looking further? Obviously, I am happy to give credit.

Sorry to raise this as an issue, but I cannot find another way to contact you.

**Comment by adcimon** [comment]
Hi! Sure, you can use it for your own work. I've already added the license.
